### ISSUE TITLE
No overall progress

### ISSUE THREAD

**Issue by mpociot** [viezel/NappDownloadManager#1]
Currently it's not possible to get an overall progress of the current download.

**Comment by viezel** [comment]
You shoud just use:

    NappDownloadManager.getAllDownloadInfo(); //prints the entire queue


or for a particular download use:

     NappDownloadManager.getDownloadInfo(url);

**Comment by viezel** [comment]
or wait.. do you mean the overall for ALL the downloads. like in total, we are 22% down (which could be derived by x downloads) ?

**Comment by mpociot** [comment]
Yes exactly. I mean the overall progress of ALL files.
In my case I'm downloading a lot of files and don't want to show a single file progress, but the overall progress.
Right now I'm calculating it myself inside the app. This works good, but it's quite expensive on resources.

**Comment by mpociot** [comment]
Android still has this issue, right?

**Comment by mpociot** [comment]
Nevermind..I just looked at the linked commit and didn't see the iOS commit :+1:
