### ISSUE TITLE
Threads won't finish

### ISSUE THREAD

**Issue by mpociot** [viezel/NappDownloadManager#3]
When downloading a large amount of files ( > 100 ) with 5 or more threads, the download will never finish.
It hangs on the last thread. Even though all files get downloaded, the last thread always tries to download the URL `null`.

When reducing the number of threads to 1 or 2 it works.

My iOS multithreading knowledge is about 0, so I doubt that I can help :(

**Comment by viezel** [comment]
ios version? 
device or sim ?

**Comment by mpociot** [comment]
I was able to reproduce this (on rollout day... :D) on iOS 7.1, 8.0, 8.1

Device only

**Comment by viezel** [comment]
there might be a magic number around 5..
http://blog.lightstreamer.com/2013/01/on-ios-url-connection-parallelism-and.html

did you try with 4 threads?

**Comment by viezel** [comment]
"The article has been updated to reflect changed conditions in iOS 7: the maximum number of connections per end-point seems to have been decreased to 4, from 5 in iOS 6."

**Comment by mpociot** [comment]
Thank you!

I'll try and report tomorrow. If that's the case, we should not allow more than 4 threads

**Comment by mpociot** [comment]
Just had the time to test it with 4 threads - with the same result.
It kept running, saying that 3 threads are still open with URL `null`

**Comment by viezel** [comment]
I believe it will be hard to figure out. 
I know that its not possible to keep a consistant number of threads every time you run the app. Its up to the OS to determine.

**Comment by mpociot** [comment]
Yes.. I believe that the module downloads all files correctly, but somehow is not closing threads.
As the download module has no "overall completed" event, it's not possible to tell if all downloads are finished.
So I need to rely on counting an internal variable on every single "completed" callback. And if it doesn't get fired, I can't determine if the app finished downloading all files or not.
