### ISSUE TITLE
Immediate Crash

### ISSUE THREAD

**Issue by nitrag** [viezel/NappDownloadManager#4]
Strange...
```
var NappDownloadManager = require('dk.napp.downloadmanager');
```
Just adding it will immediately crash the app (back to home screen). No logs. No trace.
Compiling and testing project on device.

Device: iPhone 5
OS: 8.1.3
Ti: 3.4.1GA (Alloy)

**Comment by viezel** [comment]
we are using this module in 10+ projects and have no issues. 
check if you have installed it correctly.

**Comment by nitrag** [comment]
I think I'm able to reproduce. It seems that the immediate crash happens when there is a "stuck" download. Apparently downloads, if not cancelled, will regenerate/retry when you require the module (even after quitting app??). 

Simple Reproduction:
1) Compile in Studio to Device.
2) Start a download seconds before the Studio finishes installing the app to device.
3) The app will force quit.
4) When you reload the app, the open the downloader view (require the module), it will immediately crash app.

Other weird behavior:
1) Open the downloader view (Load module, listeners, etc.)
2) Download a file. GOOD. All is working.
3) Download another file, file does not start? (due to spotty network connectivity on tethered phone?).
3b) Doesn't seem like we support timeouts.
4) Close the window*.
5) Reload download view and (sometimes) it will fire off multiple 'complete' listeners for previous downloads.

It either scenario it's like when you require the module it will try to recall the download that is stuck in Limbo. What if I don't care? I just want a new download manager for each app load. I don't want downloads to persist through app loads. 

Need ability to disable persiting.
Need ability to cancellAll() downloads. What's the difference between cancel and delete? 

To prevent some, but not all, of my problems, I'm having to do this:
```
var closeView = function(){
	NappDownloadManager.stopDownloader();
	NappDownloadManager = null;
	$.destroy();
	$.removeView();
};
```
BUT this doesn't work all the time. Because user may force quit unknowingly and not hit the close button on the view. ALSO still doesn't solve the problem where a download is stuck at 0% or 1% and never progresses further...connectivity issue of tethered phone? Introduce timeout feature?

**Comment by nitrag** [comment]
Reproduce this stall issue:

1) Load up downloader view. 
2) Download file 1, no problems.
3) Download file 2, no problems.
4) Close view.
5) Load up a different downloader view. (we're downloading different map files, so each view has different args (urls, names, etc)).
5) Start download file 1. Hangs.
6) Force quit app.
7) Load app. Go to any downloader view. Wait a few seconds. Then get "complete" event listener...????what?!
8) Try to download file on any more files. Nope. Download never starts. Repeat step 6 & 7 to complete the download.

here is code:
```
var map = arguments[0] || {};
var moment = require('moment');
var NappDownloadManager = require('dk.napp.downloadmanager');

$.title.text = map.title;

function updateMapAge(){
	var mapFile = Titanium.Filesystem.getFile(Titanium.Filesystem.applicationDataDirectory, map.mapPath);
	if (mapFile.exists()){
		if(mapFile.size <  1000)
			$.mapLast.text = "Last downloaded Map ("+map.offlineSize+"):\nDOWNLOAD ERROR, try again";
		else
			$.mapLast.text = lastDate("Map", mapFile.modificationTimestamp(), map.offlineSize);
	}else{
		$.mapLast.text = "Last downloaded Map ("+map.offlineSize+"): Never";
	}
}
updateMapAge();
function updateGeoJSONage(){
	var geoJSON = Titanium.Filesystem.getFile(Titanium.Filesystem.applicationDataDirectory, map.geoJSON);
	if (geoJSON.exists()){
		if(geoJSON.size <  400)
			$.jsonLast.text = "Last downloaded TRAILS ("+geoJSON.offlineSize+"):\nDOWNLOAD ERROR, try again";
		else
			$.jsonLast.text = lastDate("Trails", geoJSON.modificationTimestamp(), map.geoJSONsize);
	}else{
		$.jsonLast.text = "Last downloaded Trails ("+map.geoJSONsize+"): Never";
	}
}
updateGeoJSONage();

function lastDate(name, date, size){
	var text = "";
	if(moment(date).format('YY') == '69')
		text = "Last downloaded " + name + "  ("+size+"):\n Never"; 
	else
		text = "Last downloaded " + name + " ("+size+"):\n " + moment(date).format('M/D/YY h:mma');
	return text;
}

var downloading = false;
NappDownloadManager.permittedNetworkTypes = NappDownloadManager.NETWORK_TYPE_ANY;
NappDownloadManager.maximumSimultaneousDownloads = 2;
NappDownloadManager.addEventListener('progress', function(e) {
    var progress = e.downloadedBytes / e.totalBytes;
    progressBar.value = progress;
    progressBar.message = 'Downloading...' + Math.round(progress*100)+ '%'; 
});
NappDownloadManager.addEventListener('completed', function(complete){
	//NappDownloadManager.deleteItem(complete.url);
	alert('Download complete');
	Ti.API.info("Download complete:");
	Ti.API.info(complete);
	downloading = false;
	setTimeout(function(){
		updateGeoJSONage();
		updateMapAge();
	},1200);
	progressBar.value = 0;
	progressBar.hide();
});
NappDownloadManager.addEventListener('failed', function(error){
	downloading = false;
	progressBar.value = 0;
	progressBar.hide();
	Ti.API.info(error);
	NappDownloadManager.cancelItem(error.url);
	NappDownloadManager.deleteItem(error.url);
	alert('Download FAILED!');
});
NappDownloadManager.addEventListener('started', function(started){
	Ti.API.info("NappDownloadManager...here we go!!");
	Ti.API.info(started);
});

var progressBar = Titanium.UI.createProgressBar({
	width: "80%",      //describes the width
	height:50,      //describes the height
	bottom: "25%",
	min:0,            //Minimum position
	max:1,           //Maximum value for the progress
	value:0,
	color: '#fff',
	message: 'Download',
	font:{fontSize:12, fontWeight:'bold'}
});
$.configMap.add(progressBar);

function download(localFile, remoteFile, name){
	if(!downloading){
		var file = Titanium.Filesystem.getFile(Titanium.Filesystem.applicationDataDirectory, localFile);
		downloading = true;
		NappDownloadManager.addDownload({
		    name: name,
		    url: remoteFile,
		    filePath: file.nativePath,
		    priority: NappDownloadManager.DOWNLOAD_PRIORITY_NORMAL
		});
		progressBar.message = 'Downloading ' + name + '...';
		progressBar.show();
		alert("This will take some time depending on your network connection. PLEASE use WiFi if at all possible!");
	}else
		alert('Download already in progress, if the progress bar is not moving after one mintute, close this page and check your internet connection.');
}
function downloadMap(){
	download(map.mapPath, Alloy.Globals.downloadURL + map.mapPath, 'Offline Map');
}
function downloadJSON(){
	download(map.geoJSON, Alloy.Globals.downloadURL + map.geoJSON, 'Trails');
}

var closeView = function(){
	NappDownloadManager.stopDownloader();
	NappDownloadManager = null;
	$.destroy();
	$.removeView();
};
```

So is issue that you can only require NappDownloadManager once per app load? I want to be able to start with fresh instances each time. I'm not sure if adding it to Alloy.Globals would help, I don't want downloads finishing next time app is opened. I want them cleared, gone, done wether the complete or fail or timeout.

Thanks for your patience, I know I'm all over the place.

**Comment by viezel** [comment]
Current. The download manager is a singleton. 
If your app close, you will need to use the resume method. It will resume all. Remember that your server must support this.

**Comment by nitrag** [comment]
@viezel, I do not want resume. Do not care.

I do not want the module to have any memory of downloads/history,etc after I close the app or NULL the singleton.

Can we have a clear() function? 
```
NappDownloadManager.stopDownloader();
NappDownloadManager.clear(); //add this functionality
NappDownloadManager = null;
```

**Comment by mpociot** [comment]
Here's what I'm doing to do a cleanup of all started downloads:

```javascript
function cleanup()
{
	var downloadQueue = Ti.Filesystem.getFile(Ti.Filesystem.getApplicationDataDirectory(), "DownloadQueue.dat");
	if( downloadQueue.exists() )
	{
		downloadQueue.deleteFile();
	}
	var downloadCatalog = Ti.Filesystem.getFile(Ti.Filesystem.getApplicationDataDirectory(), "DownloadItemCatalog.dat");
	if( downloadCatalog.exists() )
	{
		downloadCatalog.deleteFile();
	}
}
```

**Comment by nitrag** [comment]
Getting closer to a solution. I found out that if a file exists and is already completely downloaded and the queue is empty. Then you download it again, it will try to resume the download and produce a 416 error. This error is normal. So I had to delete the file before redownloading. 

BUT
Even after your cleanup function, setting the module to null, then try to re-require the module and add a download, the download will "stall". Download never starts. Attached are two queue.dat files as examples. See if you see anything strange for me. I don't know how to open them. Question remains. Why do you have to restart the app to clear singleton from memory and be able to successfully download files again.

http://eagledevelopers.net/ryan/NappDownload-stalling.zip

Thanks for all your help so far!

**Comment by viezel** [comment]
I think so.. cause titanium sdk will cache the required modules, for the next load.

**Comment by nitrag** [comment]
Okay, all working.

Using in Alloy Globals, each time window loads:
```
if(!Alloy.Globals.NappDownloadManager)
	Alloy.Globals.NappDownloadManager = require('dk.napp.downloadmanager');
else
	Alloy.Globals.NappDownloadManager.restartDownloader();  //because the module is loaded but the Download Thread just needs a reboot!
```

Then my cleanup script that runs before view closes:
```
function cleanupDownloads()
{
    var downloadQueue = Ti.Filesystem.getFile(Ti.Filesystem.getApplicationDataDirectory(), "DownloadQueue.dat");
    if( downloadQueue.exists() )
    {
        downloadQueue.deleteFile();
    }
    var downloadCatalog = Ti.Filesystem.getFile(Ti.Filesystem.getApplicationDataDirectory(), "DownloadItemCatalog.dat");
    if( downloadCatalog.exists() )
    {
        downloadCatalog.deleteFile();
    }
}
var closeView = function(){
	Alloy.Globals.NappDownloadManager.stopDownloader();
	Alloy.Globals.NappDownloadManager.removeEventListener('completed', downloadComplete);
	Alloy.Globals.NappDownloadManager.removeEventListener('failed', downloadError);
	Alloy.Globals.NappDownloadManager.removeEventListener('started', downloadStart);
	Alloy.Globals.NappDownloadManager.removeEventListener('progress', downloadProgress);
	cleanupDownloads();
	$.destroy();
	$.removeView();
};
```

Thanks!!!
